### PR TITLE
Update to spark-3 and scala-2.12

### PR DESCRIPTION
**Pull request by jobar**
We at Wikimedia Foundation Data Engineering team use this library, and we're migrating to Spark 3 soon.
The changes are minimal for the tests to pass :)

### CODE REVIEW

**Comment by vincent-grosbois** [comment]
Hi @jobar , thanks for the PR !
I'm guessing this should probably merged into a new "spark 3" branch though?

**Comment by jobar** [comment]
A new spark-3 branch would be perfect indeed! Thank you for the fast response :)

**Comment by jobar** [comment]
And while at it I wonder - Would you release a 1.0_spark3 version of the lib onto Maven? This would make our lives incredibly easier (no need to fork internally). I know it's a burden, so please be frank :)

**Comment by alois-bissuel** [comment]
Thanks for the PR @jobar!
Regarding the branch issue, we publish artifacts only for the master branch (and I would rather want not to meddle with publishing again), thus we will merge it into the master branch. We will simply tag your commit with version 1.1 (no API change...). What do you think?

**Comment by jobar** [comment]
This would be perfect for us :) Thank you a lot for offering!

**Comment by alois-bissuel** [comment]
On the publishing side, it seems travis-CI.org is dead, and thus we have to use github CI. I will try to set it up on Monday.

**Comment by jobar** [comment]
Hello RSVD folks,
Would you by any chance have news on the publishing front?
Many thanks

**Comment by alois-bissuel** [comment]
Alas, no news on it there. We are awaiting internally the access to the sonatype password (for publishing). I will keep you updated.

**Comment by alois-bissuel** [comment]
Hello,
I did the necessary work to have the package published on Nexus. Could you confirm it works for you?

**Comment by jobar** [comment]
Hi,
We have used maven-central for the package so far - if your nexus instance is open it could work I assume.

**Comment by alois-bissuel** [comment]
I find it in https://oss.sonatype.org, but not on https://search.maven.org. Maybe maven-central will be updated soon (I have no idea if there is a link between the two).

**Comment by jobar** [comment]
Indeed, I don't see it in https://mvnrepository.com/artifact/com.criteo/rsvd
I'm gonna wait a bit and see if it gets automagically imported. Otherwise we'll use  https://oss.sonatype.org :)

**Comment by alois-bissuel** [comment]
I'll check internally if this is not the case.

**Comment by jobar** [comment]
I confirm we have access to the artifact through OSS - Many thanks for the release!

**Pull request merged**
